project_id = "vmgnlnajyvcidbyairtw"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
port = 54322
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://vmgnlnajyvcidbyairtw.supabase.co"]
jwt_expiry = 3600

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false

[functions.transactions]
verify_jwt = true

[functions.roundup]
verify_jwt = false

[functions.chatbot]
verify_jwt = false

[functions.payment-gateway]
verify_jwt = false

[functions.send-receipt]
verify_jwt = false

[functions.income-prediction]
verify_jwt = true

[functions.credit-score]
verify_jwt = true